Traceback (most recent call last):
  File "/home/Machine1/can_connector/can_connector/src/new.py", line 84, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/Machine1/can_connector/can_connector/src/new.py", line 64, in main
    await client.connect()
TypeError: object NoneType can't be used in 'await' expression
SocketcanBus was not properly shut down
